
[INTERFACE]
Address = 10.0.0.1/24   
ListenPort = 51820
PrivateKey = <HIDDEN_FOR_SECURITY>

# --- THE NETWORKING MAGIC HAPPENS HERE! ---
# These NAT  (Network Address Translation) rules connect your Virtual VPN Tunnel to the physical Oracle Internet Connection.

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[PEER]
PublicKey = <CLIENT_PUBLIC_KEY>
AllowIPs = 10.0.0.2/32
